const STATIC_STYLES = {
  NAVBAR_HEIGHT: 75,
  SIDEBAR_CLOSED_WIDTH: 70,
  SIDEBAR_OPEN_WIDTH: 240,
  SIDEBAR_TRANSITION_DURATION: "0.4s",

  TABLET_MAX_WIDTH: 834,
  MOBILE_MAX_WIDTH: 416,

  COLORS: {
    PLEX_COLOR: "#282a2d",
    DARK: "#4f4d4d",
    GRAY: "#9d9c9c",
  },
};

export { STATIC_STYLES };
