const STATIC_STYLES = {
  NAVBAR_HEIGHT: 75,
  SIDEBAR_CLOSED_WIDTH: 70,
  SIDEBAR_OPEN_WIDTH: 240,
  SIDEBAR_TRANSITION_DURATION: "0.4s",
  SEARCH_BAR_HEIGHT: 40,

  TABLET_MAX_WIDTH: 834,
  MOBILE_MAX_WIDTH: 416,
};

export { STATIC_STYLES };
