"""empty message

Revision ID: 1b33a8f77eda
Revises: 81c905106fb6
Create Date: 2021-07-13 21:28:37.805508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b33a8f77eda'
down_revision = '81c905106fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('ix_media_imdb_id')
        batch_op.drop_index('ix_media_tmdb_id')
        batch_op.drop_index('ix_media_tvdb_id')
        batch_op.create_unique_constraint(batch_op.f('uq_media_imdb_id'), ['imdb_id', 'media_type'])
        batch_op.create_unique_constraint(batch_op.f('uq_media_tmdb_id'), ['tmdb_id', 'media_type'])
        batch_op.create_unique_constraint(batch_op.f('uq_media_tvdb_id'), ['tvdb_id', 'media_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_media_tvdb_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_media_tmdb_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_media_imdb_id'), type_='unique')
        batch_op.create_index('ix_media_tvdb_id', ['tvdb_id'], unique=False)
        batch_op.create_index('ix_media_tmdb_id', ['tmdb_id'], unique=False)
        batch_op.create_index('ix_media_imdb_id', ['imdb_id'], unique=False)

    # ### end Alembic commands ###
