"""empty message

Revision ID: 2337500663a0
Revises: 
Create Date: 2021-03-21 23:38:26.280622

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
from server.database.base import DateTime

revision = "2337500663a0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("imdb_id", sa.String(), nullable=True),
        sa.Column("tvdb_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("media_type", sa.Enum("movies", "series", name="mediatype"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_imdb_id"), "media", ["imdb_id"], unique=True)
    op.create_index(op.f("ix_media_tmdb_id"), "media", ["tmdb_id"], unique=True)
    op.create_index(op.f("ix_media_tvdb_id"), "media", ["tvdb_id"], unique=True)
    op.create_table(
        "notificationagent",
        sa.Column("name", sa.Enum("email", name="agent"), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("settings", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "user",
        sa.Column("created_at", DateTime(), nullable=False),
        sa.Column("updated_at", DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("roles", sa.Integer(), nullable=True),
        sa.Column("plex_user_id", sa.Integer(), nullable=True),
        sa.Column("plex_api_key", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "friendship",
        sa.Column("pending", sa.Boolean(), nullable=True),
        sa.Column("requesting_user_id", sa.Integer(), nullable=False),
        sa.Column("requested_user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["requested_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requesting_user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("requesting_user_id", "requested_user_id"),
    )
    op.create_table(
        "mediaprovidersetting",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("ssl", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("service_name", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "provider_type",
            sa.Enum("movie_provider", "series_provider", name="mediaprovidertype"),
            nullable=False,
        ),
        sa.Column("root_folder", sa.String(), nullable=False),
        sa.Column("quality_profile_id", sa.Integer(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("anime_root_folder", sa.String(length=128), nullable=True),
        sa.Column("anime_quality_profile_id", sa.Integer(), nullable=True),
        sa.Column("language_profile_id", sa.Integer(), nullable=True),
        sa.Column("anime_language_profile_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mediaserversetting",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("ssl", sa.Boolean(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("service_name", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("server_id", sa.String(), nullable=False),
        sa.Column("server_name", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id", "server_id"),
    )
    op.create_table(
        "notification",
        sa.Column("created_at", DateTime(), nullable=False),
        sa.Column("updated_at", DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mediarequest",
        sa.Column("created_at", DateTime(), nullable=False),
        sa.Column("updated_at", DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.Enum("movies", "series", name="mediatype"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "refused", "available", name="requeststatus"),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("selected_provider_id", sa.String(), nullable=True),
        sa.Column("requesting_user_id", sa.Integer(), nullable=False),
        sa.Column("requested_user_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requested_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requesting_user_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["selected_provider_id"],
            ["mediaprovidersetting.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mediaserverlibrary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("setting_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["setting_id"],
            ["mediaserversetting.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mediaservermedia",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_media_id", sa.String(), nullable=False),
        sa.Column("added_at", sa.Date(), nullable=True),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("server_library_id", sa.Integer(), nullable=True),
        sa.Column("server_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["mediaserversetting.server_id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_library_id"],
            ["mediaserverlibrary.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "seasonrequest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("series_request_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "refused", "available", name="requeststatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["series_request_id"],
            ["mediarequest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "episoderequest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("season_request_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "refused", "available", name="requeststatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["season_request_id"],
            ["seasonrequest.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mediaserverseason",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_media_id", sa.String(), nullable=False),
        sa.Column("added_at", sa.Date(), nullable=True),
        sa.Column("season_number", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["mediaservermedia.id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["mediaserversetting.server_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mediaserverepisode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_media_id", sa.String(), nullable=False),
        sa.Column("added_at", sa.Date(), nullable=True),
        sa.Column("episode_number", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["mediaserverseason.id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["mediaserversetting.server_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mediaserverepisode")
    op.drop_table("mediaserverseason")
    op.drop_table("episoderequest")
    op.drop_table("seasonrequest")
    op.drop_table("mediaservermedia")
    op.drop_table("mediaserverlibrary")
    op.drop_table("mediarequest")
    op.drop_table("notification")
    op.drop_table("mediaserversetting")
    op.drop_table("mediaprovidersetting")
    op.drop_table("friendship")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("notificationagent")
    op.drop_index(op.f("ix_media_tvdb_id"), table_name="media")
    op.drop_index(op.f("ix_media_tmdb_id"), table_name="media")
    op.drop_index(op.f("ix_media_imdb_id"), table_name="media")
    op.drop_table("media")
    # ### end Alembic commands ###
