"""Initial migration

Revision ID: 2652c204849d
Revises: 
Create Date: 2021-02-14 21:14:33.083817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2652c204849d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('art_url', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_tmdb_id'), 'movie', ['tmdb_id'], unique=True)
    op.create_table('notificationagent',
    sa.Column('name', sa.Enum('email', name='agent'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('poster_url', sa.String(), nullable=True),
    sa.Column('art_url', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=False),
    sa.Column('number_of_seasons', sa.Integer(), nullable=True),
    sa.Column('series_type', sa.Enum('anime', 'standard', name='seriestype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('user', 'poweruser', 'superuser', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('friendship',
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requested_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('requesting_user_id', 'requested_user_id')
    )
    op.create_table('notification',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plexaccount',
    sa.Column('plex_user_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('plex_user_id', 'user_id'),
    sa.UniqueConstraint('api_key')
    )
    op.create_table('providersetting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('ssl', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('provider_type', sa.Enum('movie_provider', 'series_provider', 'media_server', name='providertype'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movierequest',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'refused', 'available', name='requeststatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('selected_provider_id', sa.String(), nullable=True),
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['requested_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['selected_provider_id'], ['providersetting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plexsetting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('server_id', sa.String(), nullable=False),
    sa.Column('server_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['providersetting.id'], ),
    sa.PrimaryKeyConstraint('id', 'server_id')
    )
    op.create_table('radarrsetting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('root_folder', sa.String(), nullable=True),
    sa.Column('quality_profile_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['providersetting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seriesrequest',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'refused', 'available', name='requeststatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('selected_provider_id', sa.String(), nullable=True),
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requested_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['selected_provider_id'], ['providersetting.id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sonarrsetting',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('root_folder', sa.String(length=128), nullable=True),
    sa.Column('anime_root_folder', sa.String(length=128), nullable=True),
    sa.Column('quality_profile_id', sa.Integer(), nullable=True),
    sa.Column('anime_quality_profile_id', sa.Integer(), nullable=True),
    sa.Column('language_profile_id', sa.Integer(), nullable=True),
    sa.Column('anime_language_profile_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['providersetting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasonrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('series_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'refused', 'available', name='requeststatus'), nullable=False),
    sa.ForeignKeyConstraint(['series_request_id'], ['seriesrequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episoderequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('season_request_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'refused', 'available', name='requeststatus'), nullable=False),
    sa.ForeignKeyConstraint(['season_request_id'], ['seasonrequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episoderequest')
    op.drop_table('seasonrequest')
    op.drop_table('sonarrsetting')
    op.drop_table('seriesrequest')
    op.drop_table('radarrsetting')
    op.drop_table('plexsetting')
    op.drop_table('movierequest')
    op.drop_table('providersetting')
    op.drop_table('plexaccount')
    op.drop_table('notification')
    op.drop_table('friendship')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('series')
    op.drop_table('notificationagent')
    op.drop_index(op.f('ix_movie_tmdb_id'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
