"""empty message

Revision ID: 81c905106fb6
Revises: c446bad70344
Create Date: 2021-06-16 23:07:21.869343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c905106fb6'
down_revision = 'c446bad70344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediaserverepisode', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('mediaservermedia', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('mediaserverseason', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediaserverseason', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('mediaservermedia', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('mediaserverepisode', schema=None) as batch_op:
        batch_op.alter_column('server_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
