[tool.poetry]
name = "cheddarr"
version = "0.1.0"
description = "Hub for media server architecture"
authors = ["Jeroli-co"]
license = "GNU GPL v3"


[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.7.0"
aiosqlite = "^0.17.0"
alembic = "^1.6.5"
appdirs = "^1.4.4"
APScheduler = "^3.7.0"
asgiref = "^3.3.4"
click = "^8.0.1"
fastapi = "^0.65.2"
emails = "^0.6"
email-validator = "^1.1.3"
gunicorn = "^20.1.0"
httpx = "^0.18.2"
itsdangerous = "^2.0.1"
Jinja2 = "^3.0.1"
loguru = "^0.5.3"
passlib =  {version = "^1.7.4", extras = ["bcrypt"]}
PlexAPI = "^4.6.1"
pydantic = "^1.8.2"
PyJWT = {version = "^2.1.0",  extras = ["crypto"]}
python-multipart = "^0.0.5"
SQLAlchemy = "^1.4.18"
tmdbsimple = "^2.8.0"
uvicorn = "^0.14.0"


[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = "^21.6b0"
flake8 = "^3.9.2"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"


[tool.black]
line-length = 99
exclude = '''

(
  /(
      \.git
    | \.venv
    | venv
    | build
    | migrations
  )/
)
'''


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
