[tool.poetry]
name = "cheddarr"
version = "0.1.0"
description = "Hub for media server architecture"
authors = ["Jeroli-co"]
license = "GNU GPL v3"


[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.6.0"
aiosqlite = "^0.17.0"
alembic = "^1.6.2"
appdirs = "^1.4.4"
APScheduler = "^3.7.0"
asgiref = "^3.3.4"
asyncclick = "7.1.2.3"
fastapi = "^0.64.0"
emails = "^0.6"
email-validator = "^1.1.2"
gunicorn = "^20.1.0"
httpx = "^0.18.1"
itsdangerous = "^1.1.0"
Jinja2 = "^2.11.3"
loguru = "^0.5.3"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
PlexAPI = "^4.5.2"
pydantic = "^1.8.1"
PyJWT = {version = "^2.1.0", extras = ["crypto"]}
python-multipart = "^0.0.5"
SQLAlchemy = "^1.4.14"
tmdbsimple = "^2.8.0"
uvicorn = "^0.13.4"


[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = "^20.8b1"
flake8 = "^3.8.4"
pytest = "^6.2.2"
pytest-asyncio = "^0.14.0"
pytest-mock = "^3.5.1"
pytest-cov = "^2.11.1"


[tool.black]
line-length = 99
exclude = '''

(
  /(
      \.git
    | \.venv
    | venv
    | build
    | migrations
  )/
)
'''


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
