[tool.poetry]
name = "cheddarr"
version = "0.1.0"
description = "Hub for media server architecture"
authors = ["Jeroli-co"]
license = "GNU GPL v3"


[tool.poetry.dependencies]
python = "^3.8"

aiofiles = "^0.6.0"
alembic = "^1.5.4"
appdirs = "^1.4.4"
APScheduler = "^3.7.0"
click = "^7.1.2"
fastapi = "^0.63.0"
emails = "^0.6"
email-validator = "^1.1.2"
gunicorn = "^20.1.0"
itsdangerous = "^1.1.0"
Jinja2 = "^2.11.3"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
PlexAPI = "^4.3.1"
pydantic = "^1.8.1"
PyJWT = {version = "^2.0.1", extras = ["crypto"]}
python-multipart = "^0.0.5"
SQLAlchemy = "^1.3.23"
requests = "^2.25.1"
tmdbsimple = "^2.8.0"
uvicorn = "^0.13.3"


[tool.poetry.dev-dependencies]
autoflake = "^1.4"
black = "^20.8b1"
flake8 = "^3.8.4"
pytest = "^6.2.2"
pytest-mock = "^3.5.1"
pytest-cov = "^2.11.1"


[tool.black]
line-length = 99
exclude = '''

(
  /(
      \.git
    | \.venv
    | venv
    | build
    | migrations
  )/
)
'''


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
