"""empty message

Revision ID: 28e76a857d3b
Revises: 4bb6fb632673
Create Date: 2020-03-22 18:50:36.903006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e76a857d3b'
down_revision = '4bb6fb632673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
