"""remove oauth

Revision ID: 2ebfca8dc6fb
Revises: a480a343a9d9
Create Date: 2020-03-26 22:57:02.205231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebfca8dc6fb'
down_revision = 'a480a343a9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_dance_oauth')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('oauth_only')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_only', sa.BOOLEAN(), nullable=True))

    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('provider_user_id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_user_id')
    )
    # ### end Alembic commands ###
