"""Initial migration

Revision ID: 351e1bac3090
Revises: 
Create Date: 2020-04-09 18:52:52.980826

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "351e1bac3090"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column(
            "email", sqlalchemy_utils.types.email.EmailType(length=255), nullable=False
        ),
        sa.Column(
            "password",
            sqlalchemy_utils.types.password.PasswordType(max_length=1137),
            nullable=False,
        ),
        sa.Column("user_picture", sqlalchemy_utils.types.url.URLType(), nullable=True),
        sa.Column("session_token", sa.String(length=256), nullable=True),
        sa.Column("confirmed", sa.Boolean(), nullable=True),
        sa.Column("api_key", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "friendship",
        sa.Column("friend_a_id", sa.Integer(), nullable=False),
        sa.Column("friend_b_id", sa.Integer(), nullable=False),
        sa.Column("pending", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["friend_a_id"], ["user.id"],),
        sa.ForeignKeyConstraint(["friend_b_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("friend_a_id", "friend_b_id"),
    )
    op.create_table(
        "provider_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(length=32), nullable=False),
        sa.Column("provider_api_key", sa.String(length=256), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_api_key"),
    )
    op.create_table(
        "plex_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plex_user_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.String(length=64), nullable=True),
        sa.Column("machine_name", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["id"], ["provider_config.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("machine_id"),
        sa.UniqueConstraint("machine_name"),
        sa.UniqueConstraint("plex_user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plex_config")
    op.drop_table("provider_config")
    op.drop_table("friendship")
    op.drop_table("user")
    # ### end Alembic commands ###
