"""empty message

Revision ID: 4bb6fb632673
Revises: da11b0c0068d
Create Date: 2020-03-22 16:53:13.996339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb6fb632673'
down_revision = 'da11b0c0068d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_only', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_picture', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_picture')
        batch_op.drop_column('oauth_only')

    # ### end Alembic commands ###
