"""Remove machine_id

Revision ID: 63b25783d0ef
Revises: 351e1bac3090
Create Date: 2020-04-25 18:27:04.886871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b25783d0ef'
down_revision = '351e1bac3090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plex_config', schema=None) as batch_op:
        batch_op.drop_column('machine_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plex_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_id', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
