"""empty message

Revision ID: 8dc3def8b2e2
Revises: f8497b0ad6e4
Create Date: 2020-04-05 15:14:09.817320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8dc3def8b2e2"
down_revision = "f8497b0ad6e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(length=32), nullable=False),
        sa.Column("provider_api_key", sa.String(length=256), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("plex_user_id", sa.Integer(), nullable=False),
        sa.Column("machine_id", sa.String(length=64), nullable=True),
        sa.Column("machine_name", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("machine_id"),
        sa.UniqueConstraint("machine_name"),
        sa.UniqueConstraint("plex_user_id"),
        sa.UniqueConstraint("provider_api_key"),
    )
    op.alter_column("user", "_password", new_column_name="password")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("provider_config")
    op.alter_column("user", "password", new_column_name="_password")
    # ### end Alembic commands ###
