"""api_key

Revision ID: a480a343a9d9
Revises: 28e76a857d3b
Create Date: 2020-03-24 20:42:17.968651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a480a343a9d9"
down_revision = "28e76a857d3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("api_key", sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("api_key")
    # ### end Alembic commands ###
