"""empty message

Revision ID: ae3629962e74
Revises: 351e1bac3090
Create Date: 2020-05-06 18:55:22.090865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3629962e74'
down_revision = '351e1bac3090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radarr_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=True),
    sa.Column('port', sa.String(length=5), nullable=True),
    sa.Column('ssl', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['provider_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sonarr_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=True),
    sa.Column('port', sa.String(length=5), nullable=True),
    sa.Column('ssl', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['provider_config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('type', sa.Enum('MEDIA_SERVER', 'MOVIE_REQUEST', 'SERIES_REQUEST', name='providertype'), nullable=True))
        batch_op.create_unique_constraint(None, ['api_key'])
        batch_op.drop_column('provider_name')
        batch_op.drop_column('provider_api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_api_key', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('provider_name', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('type')
        batch_op.drop_column('name')
        batch_op.drop_column('api_key')

    op.drop_table('sonarr_config')
    op.drop_table('radarr_config')
    # ### end Alembic commands ###
