"""friend list

Revision ID: f8497b0ad6e4
Revises: 2ebfca8dc6fb
Create Date: 2020-03-29 00:18:54.810857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8497b0ad6e4'
down_revision = '2ebfca8dc6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('friend_a_id', sa.Integer(), nullable=False),
    sa.Column('friend_b_id', sa.Integer(), nullable=False),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['friend_a_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['friend_b_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('friend_a_id', 'friend_b_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    # ### end Alembic commands ###
