"""empty message

Revision ID: fb2620ce2b64
Revises: 878bb2efd970
Create Date: 2020-09-06 16:40:19.739359

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "fb2620ce2b64"
down_revision = "878bb2efd970"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plexserver",
        sa.Column("machine_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("machine_id"),
    )
    op.create_table(
        "plexconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key", sa.String(length=256), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "provider_type",
            sa.Enum(
                "MEDIA_SERVER", "MOVIE_REQUEST", "SERIES_REQUEST", name="providertype"
            ),
            nullable=False,
        ),
        sa.Column("plex_user_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_table(
        "radarrconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key", sa.String(length=256), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "provider_type",
            sa.Enum(
                "MEDIA_SERVER", "MOVIE_REQUEST", "SERIES_REQUEST", name="providertype"
            ),
            nullable=False,
        ),
        sa.Column("host", sa.String(length=128), nullable=False),
        sa.Column("port", sa.String(length=5), nullable=True),
        sa.Column("ssl", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_table(
        "sonarrconfig",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_key", sa.String(length=256), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "provider_type",
            sa.Enum(
                "MEDIA_SERVER", "MOVIE_REQUEST", "SERIES_REQUEST", name="providertype"
            ),
            nullable=False,
        ),
        sa.Column("host", sa.String(length=128), nullable=False),
        sa.Column("port", sa.String(length=5), nullable=True),
        sa.Column("ssl", sa.Boolean(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_table(
        "plexconfigserver",
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("server_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["plexconfig.id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["plexserver.machine_id"],
        ),
    )
    op.drop_table("plex_config")
    op.drop_table("radarr_config")
    op.drop_table("sonarr_config")
    op.drop_table("provider_config")
    op.alter_column("friendship", "pending", existing_type=sa.BOOLEAN(), nullable=False)
    op.add_column(
        "user", sa.Column("avatar", sqlalchemy_utils.types.url.URLType(), nullable=True)
    )
    op.alter_column("user", "confirmed", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "user", "session_token", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    op.drop_column("user", "user_picture")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("user_picture", sa.TEXT(), nullable=True))
    op.alter_column(
        "user", "session_token", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    op.alter_column("user", "confirmed", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("user", "avatar")
    op.alter_column("friendship", "pending", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_table(
        "provider_config",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=32), nullable=False),
        sa.Column("api_key", sa.VARCHAR(length=256), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("enabled", sa.BOOLEAN(), nullable=False),
        sa.Column("type", sa.VARCHAR(length=14), nullable=True),
        sa.CheckConstraint(
            "type IN ('MEDIA_SERVER', 'MOVIE_REQUEST', 'SERIES_REQUEST')",
            name="providertype",
        ),
        sa.CheckConstraint("enabled IN (0, 1)"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_key"),
    )
    op.create_table(
        "sonarr_config",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("host", sa.VARCHAR(length=128), nullable=True),
        sa.Column("port", sa.VARCHAR(length=5), nullable=True),
        sa.Column("ssl", sa.BOOLEAN(), nullable=True),
        sa.CheckConstraint("ssl IN (0, 1)"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["provider_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "radarr_config",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("host", sa.VARCHAR(length=128), nullable=True),
        sa.Column("port", sa.VARCHAR(length=5), nullable=True),
        sa.Column("ssl", sa.BOOLEAN(), nullable=True),
        sa.CheckConstraint("ssl IN (0, 1)"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["provider_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plex_config",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("plex_user_id", sa.INTEGER(), nullable=False),
        sa.Column("machine_id", sa.VARCHAR(length=64), nullable=True),
        sa.Column("machine_name", sa.VARCHAR(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["provider_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plex_user_id"),
    )
    op.drop_table("plexconfigserver")
    op.drop_table("sonarrconfig")
    op.drop_table("radarrconfig")
    op.drop_table("plexconfig")
    op.drop_table("plexserver")
    # ### end Alembic commands ###
