name: CI

on: [push,pull_request]

jobs:
  ci:
    strategy:
      matrix:
        node-version: [13.x]
        python-version: [3.8]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build Node
      run: |
        cd client
        yarn install
        yarn run build --if-present
        yarn test
      env:
        CI: true
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.0
    - name: Poetry install
      run: poetry install
    - name: Test with pytest
      run: |
        pytest
